### ISSUE TITLE
Gradle plugin UI prompt does not respect Windows display scaling

### ISSUE THREAD

**Issue by nickavv** [StarChart-Labs/lockdown#28]
![teeny](https://cloud.githubusercontent.com/assets/1371666/26811925/bd9732d0-4a42-11e7-86cc-c08622770982.PNG)
My ownership of a 4K monitor bites me again. The prompt from the gradle plugin does not respect Windows' display scaling property, and so is rendered at half the size as everything else on my monitor

**Comment by romeara** [comment]
This is caused by the backing Java Swing application effectively lying about being DPI-aware, can't do anything for it at this end. But I did find a workaround?

From [this StackOverflow post](https://superuser.com/questions/988379/how-do-i-run-java-apps-upscaled-on-a-high-dpi-display):

Just found an easy solution on my Windows 10 machine:
- Find java.exe you installed.
- Right click -> Properties
- Go to Compatibility tab
- Check `Override high DPI scaling behavior.`
- Choose `System` for `Scaling performed by:`

**Comment by romeara** [comment]
Pull Requests are of course still welcome if anyone knows of a way to handle this with the library

**Comment by nickavv** [comment]
That's a good workaround for now, might be worthwhile to replace Swing with JavaFX in this application. The code should be largely similar and JavaFX is DPI aware
